### ISSUE TITLE
NumPad * Key is Not Mapped for Atari 5200

### ISSUE THREAD

**Issue by newoski** [libretro/libretro-atari800#11] opened 2017-10-14 16:34 UTC
NumPad * Key is Not Mapped for Atari 5200

**Comment by r-type** [comment] 2017-10-14 20:18
You mean asterisk ?if yes  It is bind to RETROK_ASTERISK.

**Comment by newoski** [comment] 2017-10-14 20:32
I'm confused. What's the difference between RETROK_ASTERISK and the "Multiply" mapping for the actual Asterisk key on a standard keyboard NumPad? 

How do I map anything to the RETROK_ASTERISK key you refer to?

**Comment by newoski** [comment] 2017-10-14 20:50
Asking my question in an easier way, what keyboard button corresponds to RETROK_ASTERISK? I've tried every single button on my keyboard, and none are a match...

**Comment by r-type** [comment] 2017-10-15 17:28
the pb is the input poll method , works fine with a azerty kb but not working with qwerty using (shift+8) because with polling method key state is on for 8 and * and shift when you hit shift and 8. 
therefore 8 is handle before * in the switch state .

```
		if(Key_Sate[RETROK_p])return AKEY_5200_PAUSE ^ shiftctrl;
		if(Key_Sate[RETROK_r])return AKEY_5200_RESET ^ shiftctrl;
		if(Key_Sate[RETROK_0])return AKEY_5200_0 ^ shiftctrl;
		if(Key_Sate[RETROK_1])return AKEY_5200_1 ^ shiftctrl;
		if(Key_Sate[RETROK_2])return AKEY_5200_2 ^ shiftctrl;
		if(Key_Sate[RETROK_3])return AKEY_5200_3 ^ shiftctrl;
		if(Key_Sate[RETROK_4])return AKEY_5200_4 ^ shiftctrl;
		if(Key_Sate[RETROK_5])return AKEY_5200_5 ^ shiftctrl;
		if(Key_Sate[RETROK_6])return AKEY_5200_6 ^ shiftctrl;
		if(Key_Sate[RETROK_7])return AKEY_5200_7 ^ shiftctrl;
		if(Key_Sate[RETROK_8])return AKEY_5200_8 ^ shiftctrl;
		if(Key_Sate[RETROK_9])return AKEY_5200_9 ^ shiftctrl;
		if(Key_Sate[RETROK_HASH])return AKEY_5200_HASH ^ shiftctrl;
		if(Key_Sate[RETROK_EQUALS])return AKEY_5200_HASH ^ shiftctrl;
		if(Key_Sate[RETROK_ASTERISK])return AKEY_5200_ASTERISK ^ shiftctrl;
```
the problem is RA side and how they deal keyboard polling . 
one solution can be to switch callback keyboard handling (use the new core option atari800_keyboard and set callbak instead of poll ).
the counterpart is callback method not working 100% the same for all platform and input driver.
try to see if it solve your problem.

**Comment by newoski** [comment] 2017-10-15 17:38
Not seeing that core option on the latest core via GUI updater on Win64

**Comment by r-type** [comment] 2017-10-15 17:41
I ve just commited it. Will be in updater after buildbot successfully built the core.

**Comment by newoski** [comment] 2017-10-15 17:46
Will it only work with Shift+8 or will it also recognize the * key on the NumPad for qwerty keyboards?

**Comment by r-type** [comment] 2017-10-15 18:03
no because on libretro * numpad key is RETROK_KP_MULTIPLY.
But I've just added a switch for it in last commit , so it should work soon .
if(Key_Sate[RETROK_KP_MULTIPLY])return AKEY_5200_ASTERISK ^ shiftctrl;

**Comment by newoski** [comment] 2017-10-15 19:09
YEAAAAAAH! I just compiled the core and * are working now. Thank you so much!

**Closed** 2017-10-15 19:35 UTC
